# Generated by Django 5.1.4 on 2024-12-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=15)),
                ('attendencestatus', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('daystatus', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=15)),
                ('employeename', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('jobtitle', models.CharField(max_length=100)),
                ('joingdate', models.DateField()),
                ('leaves', models.IntegerField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=15)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('reason', models.CharField(max_length=1000)),
                ('discription', models.CharField(max_length=750)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
