# Generated by Django 5.1.4 on 2024-12-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbvApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(max_length=1),
        ),
    ]
